# Matches nick entris using UUIDs if server is in online-mode
useNicksUUIDs = false

# Duration of caching players UUIDs
uuidCacheDuration = 600

# Avaliable types: (TOML_FILE)
[storage]
type = "TOML_FILE"
directory = "whitelists"

# Those options are applicable only when the respective plugins are present.
[integrations]
floodgate=true

[messages]
# Message sent when a player was denied access
deny = "&cYou're not invited to the party..."
